name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...
        working-directory: my-go-app

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAECREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v2
      - name: Install App Engine Go component
        run: gcloud components install app-engine-go --quiet

      - name: Deploy to Google App Engine
        id: deploy-step
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GAEPROJECTID }}
          working_directory: my-go-app

      - name: Display version URL
        run: 'curl "${{ steps.deploy-step.outputs.version_url }}"'
