name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
	  project_id: ${{ secrets.GAEPROJECTID }}
          credentials_json: ${{ secrets.GAECREDENTIALS }}
          config-file: app.yaml
